# Generated by Django 5.0.7 on 2024-07-16 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, unique=True)),
                ('observacion', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('ac', 'Active'), ('in', 'Inactive')], default='ac', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, unique=True)),
                ('telefono', models.CharField(max_length=12)),
                ('estado', models.CharField(choices=[('ac', 'Active'), ('in', 'Inactive')], default='ac', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='SeguimientoTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaIngreso', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ac', 'Active'), ('in', 'Inactive')], default='ac', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nroTramite', models.DecimalField(max_digits=10, decimal_places=0)),
                ('gestion', models.DecimalField(max_digits=4, decimal_places=0, default=2024)),
                ('tipoTramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrotramite.tipotramite')),
                ('unidadOrigen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrotramite.unidad')),
            ],
        ),
    ]
