# Generated by Django 5.0.7 on 2024-07-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrotramite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimientotramite',
            name='gestion',
        ),
        migrations.AddField(
            model_name='seguimientotramite',
            name='gestionTramite',
            field=models.DecimalField(decimal_places=0, default=2024, max_digits=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unidad',
            name='telefono',
            field=models.DecimalField(decimal_places=0, max_digits=11),
        ),
    ]
