# Generated by Django 5.0.7 on 2024-07-23 20:58

import django.db.models.deletion
import registrotramite.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrotramite', '0002_remove_seguimientotramite_gestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientotramite',
            name='gestionTramite',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='seguimientotramite',
            name='nroTramite',
            field=models.DecimalField(decimal_places=0, max_digits=10, validators=[registrotramite.validators.validar_par]),
        ),
        migrations.CreateModel(
            name='TramiteTraza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaIngreso', models.DateTimeField(auto_now_add=True)),
                ('fechaSalida', models.DateTimeField()),
                ('estado', models.CharField(choices=[('ac', 'Active'), ('in', 'Inactive')], default='ac', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('seguimientoTramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrotramite.seguimientotramite')),
                ('unidadActual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrotramite.unidad')),
            ],
        ),
    ]
