# Generated by Django 5.0.7 on 2024-07-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrotramite', '0003_alter_seguimientotramite_gestiontramite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramitetraza',
            name='fechaSalida',
            field=models.DateTimeField(blank=True),
        ),
    ]
